services:
  - type: web
    name: kryptos-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.1"
      - key: ETHERSCAN_API_KEY
        sync: false
      - key: DEPLOYER_PRIVATE_KEY
        sync: false
      - key: PINATA_JWT
        sync: false
      - key: PINATA_API_KEY
        sync: false
      - key: PINATA_SECRET_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: BASE_SEPOLIA_RPC
        value: https://base-sepolia-rpc.publicnode.com
